// <auto-generated />
using System;
using LinkedIn.JobScraper.Web.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkedIn.JobScraper.Web.Persistence.Migrations
{
    [DbContext(typeof(LinkedInJobScraperDbContext))]
    [Migration("20260306101138_AddAppUserSuperAdminFlag")]
    partial class AddAppUserSuperAdminFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AiBehaviorSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("BehavioralInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExclusionSignals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputLanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PrioritySignals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("AiBehaviorSettings", (string)null);
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AiGlobalShortlistItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concerns")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("Confidence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("int");

                    b.Property<Guid>("JobRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LatencyMilliseconds")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("int");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("RecommendationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("TotalTokenCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobRecordId");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "Decision");

                    b.HasIndex("RunId", "JobRecordId")
                        .IsUnique();

                    b.HasIndex("RunId", "Rank")
                        .IsUnique();

                    b.ToTable("AiGlobalShortlistItems", (string)null);
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AiGlobalShortlistRunCandidateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("JobRecordId");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "JobRecordId")
                        .IsUnique();

                    b.HasIndex("RunId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("AiGlobalShortlistRunCandidates", (string)null);
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AiGlobalShortlistRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("NeedsReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("NextSequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("int");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ShortlistedCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("AppUserId", "CreatedAtUtc");

                    b.HasIndex("AppUserId", "Status");

                    b.ToTable("AiGlobalShortlistRuns", (string)null);
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AppUserRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.JobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiConcerns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiLabel")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("AiScore")
                        .HasColumnType("int");

                    b.Property<string>("AiSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiWhyMatched")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyApplyUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailContentFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EmploymentStatus")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("FirstDiscoveredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastDetailSyncedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastScoredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LinkedInJobCardUrn")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LinkedInJobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LinkedInJobPostingUrn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LinkedInUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ListedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LocationName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("AiLabel");

                    b.HasIndex("AiScore");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("LastDetailSyncedAtUtc");

                    b.HasIndex("LastSeenAtUtc");

                    b.HasIndex("LinkedInUpdatedAtUtc");

                    b.HasIndex("ListedAtUtc");

                    b.HasIndex("AppUserId", "LinkedInJobId")
                        .IsUnique();

                    b.HasIndex("AppUserId", "LinkedInJobPostingUrn")
                        .IsUnique();

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.JobStatusHistoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("JobRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("JobRecordId", "ChangedAtUtc");

                    b.ToTable("JobStatusHistory", (string)null);
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.LinkedInSearchSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<bool>("EasyApply")
                        .HasColumnType("bit");

                    b.Property<string>("JobTypeCodesCsv")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("LocationDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LocationGeoId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LocationInput")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WorkplaceTypeCodesCsv")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("LinkedInSearchSettings", (string)null);
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.LinkedInSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastValidatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestHeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "SessionKey")
                        .IsUnique();

                    b.ToTable("LinkedInSessions", (string)null);
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AiBehaviorSettingsRecord", b =>
                {
                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.AppUserRecord", "AppUser")
                        .WithMany("AiBehaviorSettings")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AiGlobalShortlistItemRecord", b =>
                {
                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.JobRecord", "JobRecord")
                        .WithMany("GlobalShortlistItems")
                        .HasForeignKey("JobRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.AiGlobalShortlistRunRecord", "Run")
                        .WithMany("Items")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRecord");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AiGlobalShortlistRunCandidateRecord", b =>
                {
                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.JobRecord", "JobRecord")
                        .WithMany("GlobalShortlistRunCandidates")
                        .HasForeignKey("JobRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.AiGlobalShortlistRunRecord", "Run")
                        .WithMany("Candidates")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRecord");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AiGlobalShortlistRunRecord", b =>
                {
                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.AppUserRecord", "AppUser")
                        .WithMany("AiGlobalShortlistRuns")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.JobRecord", b =>
                {
                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.AppUserRecord", "AppUser")
                        .WithMany("Jobs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.JobStatusHistoryRecord", b =>
                {
                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.JobRecord", "JobRecord")
                        .WithMany("StatusHistory")
                        .HasForeignKey("JobRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRecord");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.LinkedInSearchSettingsRecord", b =>
                {
                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.AppUserRecord", "AppUser")
                        .WithMany("LinkedInSearchSettings")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.LinkedInSessionRecord", b =>
                {
                    b.HasOne("LinkedIn.JobScraper.Web.Persistence.Entities.AppUserRecord", "AppUser")
                        .WithMany("LinkedInSessions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AiGlobalShortlistRunRecord", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.AppUserRecord", b =>
                {
                    b.Navigation("AiBehaviorSettings");

                    b.Navigation("AiGlobalShortlistRuns");

                    b.Navigation("Jobs");

                    b.Navigation("LinkedInSearchSettings");

                    b.Navigation("LinkedInSessions");
                });

            modelBuilder.Entity("LinkedIn.JobScraper.Web.Persistence.Entities.JobRecord", b =>
                {
                    b.Navigation("GlobalShortlistItems");

                    b.Navigation("GlobalShortlistRunCandidates");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
